services:
  vue:
    container_name: vue
    build:
      context: vue-app
      dockerfile: dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./vue-app:/workspace
    environment:
      - TZ=Asia/Seoul
    command: sleep infinity
